version: '3.8'

services:
  # Aplicación principal
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dolibarr-modern-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - APP_NAME=Dolibarr Modern Frontend
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8080
      
      # Base de datos (opcional - si usas base de datos local)
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=dolibarr_frontend
      - DB_USERNAME=dolibarr_user
      - DB_PASSWORD=secure_password
      
      # Configuración de sesiones
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=
      
      # Cache
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      
      # Dolibarr API (CONFIGURAR SEGÚN TU INSTALACIÓN)
      - DOLIBARR_BASE_URL=https://gestion.carlos-herrera.consulting/api/index.php
      - DOLIBARR_API_KEY=your_dolibarr_api_key_here
      
      # CORS
      - CORS_ALLOWED_ORIGINS=http://localhost:8080,https://your-domain.com
      
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - db
    networks:
      - dolibarr-network

  # Base de datos MySQL (opcional)
  db:
    image: mysql:8.0
    container_name: dolibarr-frontend-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=dolibarr_frontend
      - MYSQL_USER=dolibarr_user
      - MYSQL_PASSWORD=secure_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - dolibarr-network

  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    container_name: dolibarr-frontend-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dolibarr-network

  # Nginx como proxy reverso (opcional para producción)
  nginx:
    image: nginx:alpine
    container_name: dolibarr-frontend-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - dolibarr-network

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

networks:
  dolibarr-network:
    driver: bridge
