version: '3.8'

services:
  app:
    build: .
    container_name: dolibarr-modern-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      # Configuraci칩n b치sica de Laravel
      - APP_NAME=Dolibarr Modern Frontend
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=${APP_URL:-http://localhost:8080}
      
      # Configuraci칩n de Dolibarr (OBLIGATORIO CONFIGURAR)
      - DOLIBARR_BASE_URL=${DOLIBARR_BASE_URL}
      - DOLIBARR_API_KEY=${DOLIBARR_API_KEY}
      
      # Configuraci칩n interna (no modificar)
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      
      # CORS
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:8080}
      - CORS_SUPPORTS_CREDENTIALS=true
      
    volumes:
      - app_storage:/var/www/html/storage
      - app_cache:/var/www/html/bootstrap/cache
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  app_storage:
    driver: local
  app_cache:
    driver: local
